RO string bug fix
Fixed bug reported by Tim Van der Hulst:

-------------------------------------------------------------------------------
dofile('/mmc/test.lua') -- OK
require('test') -- Fail!!

-------------
/mmc
test.txt                       5 bytes
gprs.lua                       2910 bytes
util.lua                       385 bytes
test.lua                       385 bytes

Total on /mmc: 3685 bytes

-------------

Error: [string "xmodem"]:23: module 'test' not found:
        no field package.preload['test']
        no file '/mmc/test.lua;/mmc/test.lc;/rom/test.lua;/rom/test.lc'
        no file '/mmc/test.lc;/rom/test.lua;/rom/test.lc'
        no file '/rom/test.lua;/rom/test.lc'
        no file '/rom/test.lc'
-------------------------------------------------------------------------------

The problem was actually in the way read-only strings were created. If a read-only
string creation call specified a size which was different than the actual (C) size
of the string, the string didn't get null-terminated, which in turn led to some
interesting errors (like the one above).